language: ruby
before_install:
  - gem install bundler
before_script:
  - bundle update
cache: bundler
rvm:
  - 2.2.9
  - 2.3.6
  - 2.4.3
  - 2.5.0
gemfile:
  - gemfiles/unicorn44.gemfile
  - gemfiles/unicorn45.gemfile
  - gemfiles/unicorn46.gemfile
  - gemfiles/unicorn47.gemfile
  - gemfiles/unicorn48.gemfile
  - gemfiles/unicorn49.gemfile
  - gemfiles/unicorn50.gemfile
matrix:
  fast_finish: true
bundler_args: --jobs 3 --retry 3
